from tkinter import *
root=Tk()
root.geometry('500x200')
root.title("Mouse Events for Voice Input:")
root.config(bg='lightblue')
name1=Label(root,text="For Clicking :voice input is:\n click on link one")
name1.config(bg='lightgreen')
name1.pack()
name2=Label(root,text="For scrolling down :voice input is:\n scroll down")
name2.config(bg='lightgreen')
name2.pack()
name3=Label(root,text="For scrolling upward :voice input is:\n scroll upward")
name3.config(bg='lightgreen')
name3.pack()
name4=Label(root,text="For scrolling at top of page :voice input is: \nscroll at the top")
name4.config(bg='lightgreen')
name4.pack()
name5=Label(root,text="For scrolling at bottom of page :voice input is: \nscroll at the bottom")
name5.config(bg='lightgreen')
name5.pack()
root.mainloop()
def quit(self):
    self.root.destroy()
    return quit(self)
